/**
 * Centralized UI strings for localization support.
 * Currently supports English (en).
 * In the future, this can be expanded to multiple files (en.ts, ar.ts, etc.)
 * and managed via an i18n library or a simple context provider.
 */

export const STRINGS = {
  common: {
    continue: 'Continue',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    welcome: 'Welcome',
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    playing: 'Playing...',
    listen: 'Listen',
    listenRepeat: 'Listen & Repeat',
    slow: 'Slow',
    levelBasic: 'Basic',
    levelIntermediate: 'Intermediate',
    levelAdvanced: 'Advanced',
    home: 'Home',
    soon: 'Soon',
    begin: 'Begin',
  },
  onboarding: {
    welcomeTitle: 'Gulf Arabic, for Real Dubai Life',
    welcomeSubtitle: 'Learn through real stories, not textbooks',
    helloKaf: 'Salam! I am Kaf.',
    keepGoingMascot: 'Keep tapping!',
    letsBegin: 'Let\'s begin!',
    liveScenarios: (count: number) => `${count} Live Scenarios`,
    phrasesCount: (count: number) => `${count}+ Phrases`,
    beginJourney: 'Begin Journey',
    freeToStart: 'Free to start • No credit card',
    stepXofY: (x: number, y: number) => `STEP ${x} OF ${y}`,
    choosePath: 'Choose your path',
    careerMode: 'Career Mode',
    careerSub: 'Hospitality · Retail · Office',
    careerDesc: 'Focus on business etiquette, formal greetings, and workplace culture.',
    socialMode: 'Social Flow',
    socialSub: 'Friends & Family',
    socialDesc: 'Master casual conversation, dining etiquette, and everyday interactions.',
    whatsYourName: 'What\'s your name?',
    kafGreetingSub: 'Kaf will greet you every morning',
    placeholderName: 'Enter your name',
    genderQuestion: 'How should Arabic address you?',
    genderWhy: 'Arabic changes ending depending on who is speaking — we\'ll teach you the forms you\'ll actually use',
    genderMale: 'Masculine',
    genderMaleExample: 'أنا يديد · مشغول',
    genderFemale: 'Feminine',
    genderFemaleExample: 'أنا يديدة · مشغولة',
    welcomeName: (name: string) => `"Welcome, ${name}"`,
    keepTyping: 'Keep typing...',
    mascotTitle: 'Meet your companion',
    mascotSubtitle: 'They\'ll guide you through every Arabic lesson',
    mascotMayaTagline: 'Your warm & friendly guide',
    mascotMaxTagline: 'Your sharp & clever companion',
    whatsYourRole: 'What\'s your role?',
    roleTailored: 'We\'ll tailor your experience',
    whatsDrivesYou: 'What drives you?',
    selectEverything: 'Select everything that applies',
    goalCount: (count: number) => `${count} goals selected`,
    buildRoutine: 'Build a routine',
    routineSub: 'Consistency is the key to mastery',
    tips: ['Daily 5-min practice', 'Real-world scenarios', 'Track your progress'],
    keepGoing: 'Keep Going',
    makeCommitment: 'Make a commitment',
    committed: 'Committed!',
    commitmentSub: 'Hold to commit to your daily habit',
    dailyHabit: 'Commit to learning for 5 minutes a day',
    skipForNow: 'Skip for now',
    freeTrialBadge: '4-day free trial',
    paywallTitle: "Don't lose your learning momentum",
    paywallSub: "Keep your progress and get unlimited access to Khaleeji scenarios",
    startFreeTrial: 'Keep My Unlocked Progress',
    cancelAnytime: 'Cancel anytime',
    everythingIncluded: 'Everything included',
    oneSubscription: 'One subscription, the full Fasih experience',
    satisfactionGuarantee: 'Satisfaction Guarantee',
    refundGuarantee: 'Full refund if you\'re not satisfied',
    refundPolicy: '7-day money back guarantee',
    seePlans: 'Lock In My Path to Fluency',
    choosePlan: 'Secure your premium access',
    trialCancel: "Don't miss out on premium access · Cancel anytime",
    savePct: (pct: number) => `Save ${pct}%`,
    yearlyPlan: 'Yearly Plan',
    yearlyBest: 'Best for committed learners',
    monthlyPlan: 'Monthly Plan',
    monthlyFlex: 'Maximum flexibility',
    billingYearly: (yearPrice: string, savings: string) => `Billed ${yearPrice}/year • Saves ${savings}`,
    perMonth: '/month',
    skipUnlock: 'Skip — unlock by completing 3 scenarios',
    skipWarningTitle: 'Are you sure you want to leave?',
    skipWarningMessage: "You've already set up your custom learning path and unlocked Gulf Arabic phrases. Skipping now means you won't save this progress.",
    skipWarningConfirm: 'Continue Without Saving',
    skipWarningCancel: 'Go Back to Onboarding',
    roles: {
      hospitality: 'Hospitality',
      food_beverage: 'Food & Beverage',
      retail_sales: 'Retail & Sales',
      health_wellness: 'Health & Wellness',
      transport_logistics: 'Transport & Logistics',
      property_facilities: 'Property & Facilities',
      office_corporate: 'Office & Corporate',
      education_childcare: 'Education & Childcare',
    },
    pickYourRole: 'What\'s your specific role?',
    goals: {
      professional: { label: 'Professional Growth', sub: 'Better career opportunities' },
      friends: { label: 'Connect with Friends', sub: 'Build deeper relationships' },
      culture: { label: 'Cultural Appreciation', sub: 'Understand the local heritage' },
      daily: { label: 'Daily Navigation', sub: 'Handle errands with ease' },
      career: { label: 'Career Advancement', sub: 'Stand out in your field' },
    },
    timeline: [
      { day: 'Day 1', title: 'Unlock Scenarios', desc: 'Get access to all interactive real-world simulations.' },
      { day: 'Day 2', title: 'Smart Review', desc: 'AI-powered retention to master phrases forever.' },
      { day: 'Day 3', title: 'Habit Formation', desc: 'Receive personalized motivation to keep you going.' },
      { day: 'Day 4', title: 'Trial Ends', desc: 'Continue your journey with full premium benefits.' },
    ],
    features: [
      { label: 'Voice Practice', sub: 'Unlimited sessions' },
      { label: 'Phrase Library', sub: '500+ expressions' },
      { label: 'All Scenarios', sub: '40+ situations' },
      { label: 'Cultural Notes', sub: 'Deep context' },
      { label: 'Achievements', sub: 'Badges & levels' },
      { label: 'Career Paths', sub: '5 industries' },
    ],
  },
  home: {
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    welcomeFasih: 'Welcome to Fasih',
    newUserTip: 'Start your first scenario to begin tracking your mastery across categories.',
    checklistProgress: (done: number, total: number) => `${done}/${total} steps done — keep going!`,
    learningDaysTitle: 'Learning Days',
    gettingStartedTitle: 'Getting Started',
    daysLearning: (count: number) => `${count} Day Streak`,
    studiedCount: 'Phrases Studied',
    scenariosCount: 'Scenarios Done',
    readyForReview: (count: number) => `${count} phrases ready to review`,
    revisitPhrases: 'Revisit what you\'ve learned to improve retention.',
    continueLearning: 'Continue Learning',
    beginScenario: 'Begin Scenario',
    practiceRealConversations: 'Practice real conversations and learn cultural nuance.',
    yourLearning: 'Your Learning',
    noProgressYet: 'No progress yet',
    listenLearn: 'Listen & Learn',
    practiceMode: 'Practice Mode',
    studiedPhrases: (count: number) => `${count} phrases`,
    reviewReady: 'Review Ready',
    featuredAuthor: 'By Fasih Team',
    durationMinutes: (min: number) => `Duration: ${min} minutes`,
  },
  streakRisk: {
    bannerTitle: (days: number) => `Your ${days}-day streak ends tonight`,
    bannerSub: 'Practice for 5 minutes, or use a Streak Freeze to protect it.',
    practiceNow: 'Practice Now',
    useFreeze: (count: number) => `Use Freeze (${count} left)`,
    notificationTitle: (days: number) => `🔥 ${days}-day streak at risk`,
    notificationBody: "Don't lose it — 5 minutes keeps it alive.",
  },
  phrases: {
    title: 'Phrase Library',
    subtitle: (count: number) => `${count} Gulf Arabic expressions`,
    searchPlaceholder: 'Arabic, English, or phonetic...',
    filterAll: 'All',
    categoryFilterLabel: 'Category',
    levelFilterLabel: 'Level',
    expressionCount: (count: number) => `${count} expression${count !== 1 ? 's' : ''}`,
    playSlowly: 'Play slowly',
    pronunciation: 'Pronunciation',
    culturalContext: 'Cultural Context',
    noPhrasesFound: 'No phrases found',
    noPhrasesSub: 'Try a different search or category',
    categoriesTitle: 'Categories',
    topicsCount: (count: number) => `${count} topics`,
    browseAllTitle: 'Browse All Phrases',
    browseAllSub: (phraseCount: number, categoryCount: number) => `${phraseCount} expressions across ${categoryCount} categories`,
    fromFirstScenario: 'From your first scenario',
  },
  practice: {
    title: 'Practice',
    flashcards: 'Flashcards',
    quiz: 'Translation Quiz',
    reverseQuiz: 'Reverse Quiz',
    phraseBuilder: 'Phrase Builder',
    results: 'Results',
    xOfY: (x: number, y: number) => `${x} of ${y}`,
    correctCount: (count: number) => `${count} correct`,
    chooseHowToPractice: 'Choose how you want to practice',
    flashcardDesc: 'See Arabic phrases, tap to reveal the meaning. Rate your knowledge after each card.',
    flashcardMeta: (dueCount: number) => dueCount > 0 ? `${dueCount} due · SRS-driven` : 'All caught up · reviewing early',
    quizTitle: 'Translation Quiz',
    quizDesc: 'Read the Arabic phrase, choose the correct English translation from four options.',
    quizMeta: (count: number) => `${count} questions · Multiple choice`,
    reverseQuizDesc: 'See the English meaning, choose the correct Arabic phrase. Tests real recall.',
    reverseQuizMeta: (count: number) => `${count} questions · Active recall`,
    pickTheArabic: 'Pick the Arabic phrase',
    matchPronunciation: 'Match the pronunciation',
    phraseBuilderDesc: 'See the English meaning, tap word tiles to build the Arabic phrase in order.',
    phraseBuilderMeta: (count: number) => `${count} phrases · Tap to place`,
    tapToReveal: 'Tap to reveal',
    howWellDidYouKnow: 'How well did you know this?',
    newToMe: 'New to me',
    learning: 'Learning',
    knewIt: 'Knew it',
    newToMeSub: 'Back in 1 day',
    learningSub: 'Back in 3 days',
    knewItSub: 'Back in 7 days',
    translateThis: 'Translate this phrase',
    seeYourResult: 'See Your Result',
    excellentResult: 'Excellent! Your Arabic is growing fast.',
    goodResult: 'Good effort! Keep practicing.',
    keepGoingResult: 'Keep going — every new phrase is a step forward.',
    missed: 'Missed',
    phrasesReviewed: (count: number) => `${count} phrases reviewed`,
    practiceAgain: 'Practice Again',
    next: 'Next',
    seeResults: 'See Results',
    noCardsTitle: 'No phrases to practice',
    noCardsSub: 'Add phrases to your library first',
  },
  scenarios: {
    title: 'Scenarios',
    subtitle: 'Choose a situation to practice',
    career: 'Career',
    social: 'Social',
    decisions: (count: number) => `${count} decisions`,
    phrases: (count: string | number) => `${count} phrases`,
    phrasesTeaser: (count: string | number) => `This scenario teaches ${count} phrases. Complete it to unlock them.`,
    phrasesAdded: (count: number) => `${count} phrases added`,
    decisionLabel: (count: number) => count === 1 ? 'decision' : 'decisions',
    phraseLabel: (count: number) => count === 1 ? 'phrase' : 'phrases',
    outcomeLabel: (count: number) => count === 1 ? 'outcome' : 'outcomes',
    comingSoon: (count: number, mode: string) => `${count} more ${mode} scenario${count === 1 ? '' : 's'} coming soon`,
    writingNext: 'We are writing the next conversations now.',
    notAvailable: (id: string) => `No script available for "${id}". This scenario may be coming soon.`,
    noScript: (id: string) => `No script available for "${id}". This scenario may be coming soon.`,
    scenarioNotFound: 'Scenario not found',
    notFound: 'Scenario not found',
    noScenesTitle: 'No scenes available',
    noScenesSub: "This scenario doesn't have any content yet",
    goBack: 'Go Back',
    playing: 'Playing...',
    listen: 'Listen',
    seeResult: 'See your result',
    continue: 'Continue',
    begin: 'Begin Journey',
    relationshipTitle: 'Relationship Impact',
    finalOutcome: 'Final Outcome',
    trust: 'Trust',
    respect: 'Respect',
    culture: 'Culture',
    kafSays: 'Kaf says',
    introDesc: 'Ahmed, your Emirati colleague, invites you for coffee. Every choice shapes your relationship.',
    kafIntro: 'Coffee is never just coffee in Emirati culture — it is an invitation to build trust.',
    outcomesSummary: 'Family Partnership · Job Referral · Transactional · Missed',
    charSaid: (name: string) => `${name}:`,
    culturalIntelligence: 'Cultural Intelligence',
    chooseYourResponse: 'Choose your response',
    chooseResponse: 'Choose your response',
    retry: 'Retry',
    home: 'Home',
    totalScore: (score: number) => `Total Score: ${score}`,
    listenVoice: (gender: string) => `Listen to ${gender === 'female' ? 'her' : 'him'}`,
    listenAndRepeat: 'Say the phrase you just chose out loud.',
    outcomeLabelMap: {
      excellent: 'Excellent Connection',
      good: 'Positive Greeting',
      neutral: 'Polite but Transactional',
      poor: 'Missed Opportunity',
      bad: 'Missed Opportunity',
    },
    phrasesUnlocked: (count: number) => `${count} phrase${count !== 1 ? 's' : ''} unlocked`,
    phrasesUnlockedSub: 'Tap any card to hear the pronunciation',
    culturalJourneyTitle: 'Your Cultural Journey',
    endingDiscovery: (total: number) => `1 of ${total} possible endings`,
    tryDifferentChoices: 'Play again with different choices to find another path',
    communityEnding: (pct: number) => pct > 0 ? `${pct}% of players reach this ending` : 'One of the first players to reach this ending',
    communityEndingSecret: (pct: number) => pct > 0 ? `Only ${pct}% of players ever find this — you just did` : 'Almost no one finds this ending. You did.',
    communityChoice: (pct: number) => `${pct}% of learners made this choice`,
    secretEndingExists: 'This scenario has a hidden ending. Most players miss it.',
    secretEndingTeaser: 'There\'s an ending you haven\'t found yet. It unlocks when you make the right choices at every step — play again to find it.',
    practiceThesePhrases: 'Practice These Phrases',
    tryAgain: 'Try Again',
  },
  profile: {
    title: 'Your Journey',
    learner: 'Learner',
    daysActive: 'Days Active',
    studied: 'Studied',
    mastered: 'Mastered',
    scenarios: 'Scenarios',
    dayLearning: 'Day Learning',
    daysLearning: 'Days Learning',
    skillAreas: 'Skill Areas',
    accuracy: (acc: number) => `${acc}% accuracy`,
    yourGoals: 'Your Goals',
    milestones: 'Milestones',
    journal: 'Cultural Journal',
    stats: {
      streak: 'Day Streak',
      points: 'Experience',
      accuracy: 'Accuracy',
    },
    goals: {
      title: 'Active Goals',
      empty: 'Select goals in settings to track your progress',
    },
    arabicForms: {
      title: 'Arabic Forms',
      subtitle: 'Arabic changes ending depending on who is speaking. This sets which forms we teach you — and unlocks scenarios written for one gender.',
    },
    dailyGoal: {
      title: 'Daily Goal',
      casual: 'Casual',
      casualSub: '250 XP/day',
      regular: 'Regular',
      regularSub: '500 XP/day',
      intense: 'Intense',
      intenseSub: '750 XP/day',
    },
    appearance: 'Appearance',
    appearanceModes: {
      light: 'Light',
      dark: 'Dark',
      system: 'System',
    },
    theme: 'Theme',
    dark: 'Dark Mode',
    vibrant: 'Vibrant Colors',
    vibrantSub: 'Enable rich gradients and decorative washes',
    language: {
      title: 'Language',
      select: 'Interface Language',
    },
    learningMode: {
      title: 'Learning Mode',
      career: 'Career',
      careerDesc: 'Work scenarios',
      social: 'Social',
      socialDesc: 'Daily life',
    },
    subscription: {
      title: 'Subscription',
      proName: 'Fasih Pro',
      active: 'Active subscription',
      manage: 'Manage Subscription',
      restore: 'Restore Purchases',
      upgradeTitle: 'Upgrade to Fasih Pro',
      upgradeDesc: 'Unlock all scenarios & features',
    },
    account: 'Account',
    notifications: 'Notifications',
    enabled: 'Enabled',
    disabled: 'Disabled',
    displayLanguage: 'Display Language',
    aboutFasih: 'About Fasih',
    version: (v: string) => `v${v}`,
    signOut: 'Sign Out',
    deleteAccount: {
      button: 'Delete Account',
      title: 'Delete your account?',
      message:
        'This permanently erases your streak, progress, saved phrases and journal entries. It cannot be undone, and we cannot recover any of it afterwards.',
      /** Appended when the user has an active subscription — deleting the account does NOT cancel billing. */
      subscriptionWarning:
        '\n\nYour subscription is billed by the App Store, not by Fasih, so deleting your account does not cancel it. Cancel it in your device Subscriptions settings first, or you will keep being charged.',
      confirm: 'Delete Forever',
      deleting: 'Deleting…',
      failedTitle: 'Could not delete your account',
      failedMessage: (reason: string) =>
        `Nothing has been deleted — your account and data are intact. Please try again.\n\n${reason}`,
      /** Cloud data deleted, but removing the Clerk account itself failed. */
      partialTitle: 'Your data was deleted',
      partialMessage:
        'Your learning data has been erased, but we could not remove the account itself. Please contact support so we can finish removing it.',
    },
  },
  legal: {
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
  },
  auth: {
    rateLimited: 'Too many attempts — please wait a bit and try again.',
    signIn: {
      title: 'Sign in to your Account',
      noAccount: 'Don\'t have an account?',
      signUpLink: 'Sign Up',
      emailPlaceholder: 'Email address',
      passwordPlaceholder: 'Password',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      forgotPassword: 'Forgot Your Password?',
      logIn: 'Log In',
      signingIn: 'Signing In...',
      signInFailed: 'Sign in failed',
      skipDevOnly: 'Skip (dev only)',
    },
    signUp: {
      passwordRuleLength: '6+ characters',
      passwordRuleUpper: 'One uppercase',
      passwordRuleNumber: 'One number',
      createAccountTitle: 'Create Account',
      verifyEmailTitle: 'Verify Email',
      alreadyHaveAccount: 'Already have an account?',
      signInLink: 'Sign In',
      codeSentTo: (email: string) => `We sent a 6-digit code to ${email}`,
      verificationCodePlaceholder: 'Enter verification code',
      verifying: 'Verifying...',
      verifyEmail: 'Verify Email',
      backToSignUp: '← Back to sign up',
      fullNamePlaceholder: 'Full name',
      emailPlaceholder: 'Email address',
      passwordPlaceholder: 'Create password',
      // Split so Terms / Privacy render as tappable links inside the sentence.
      agreeTermsPrefix: 'I agree to the',
      agreeTermsConjunction: 'and',
      /** Whole sentence, for the checkbox's screen-reader label. */
      agreeTermsAccessible: 'I agree to the Terms of Service and Privacy Policy',
      createAccount: 'Create Account',
      creatingAccount: 'Creating Account...',
      skipDevOnly: 'Skip (dev only)',
      signUpFailed: 'Sign up failed',
      verificationFailed: 'Verification failed',
    },
    forgotPassword: {
      title: 'Forgot Password?',
      setNewPasswordTitle: 'Set New Password',
      sendCodeSub: 'No worries, we\'ll send you a reset code',
      resetCodeSub: (email: string) => `Enter the code sent to ${email} and choose a new password`,
      emailInstructions: 'Enter your email and we\'ll send you a reset code',
      emailPlaceholder: 'Email address',
      sendResetCode: 'Send Reset Code',
      sending: 'Sending...',
      codePlaceholder: '6-digit code',
      newPasswordPlaceholder: 'New password (6+ chars)',
      resetPassword: 'Reset Password',
      resetting: 'Resetting...',
      back: '← Back',
      rememberPassword: 'Remember your password?',
      signInLink: 'Sign In',
      requestCodeFailed: 'Could not send reset email',
      resetFailed: 'Reset failed',
    },
  },
  ui: {
    emptyState: {
      title: 'Nothing here yet',
      subtitle: 'Try starting a new activity to see progress',
    },
    errorBoundary: {
      title: 'Oops! Something went wrong',
      subtitle: 'Something went wrong inside the app. Please try again.',
      button: 'Try Again',
    },
    featureGate: {
      locked: (name: string) => `Locked: ${name}`,
      completeMore: (count: number, name: string) => `Complete ${count} more scenario${count > 1 ? 's' : ''} to unlock ${name}.`,
      goToScenarios: 'Go to Scenarios',
    },
  },
};
